export class Pokemon {
  nom: string;
  pokedexId: number;
  type1: string;
  type2: string;
  total: number;
  pv: number;
  att: number;
  def: number;
  attspe: number;
  defspe: number;

  constructor(pokemon?: Partial<Pokemon>) {
    Object.assign(this, pokemon);
  }
}


export const POKEMONS: Pokemon[] = [
    {
      pokedexId: 1,
      nom: 'Bulbasaur',
      type1: 'Grass',
      type2: 'Poison',
      total: 318,
      pv: 45,
      att: 49,
      def: 49,
      attspe: 65,
      defspe: 65,
    },
    {
      pokedexId: 2,
      nom: 'Ivysaur',
      type1: 'Grass',
      type2: 'Poison',
      total: 405,
      pv: 60,
      att: 62,
      def: 63,
      attspe: 80,
      defspe: 80,
    },
    {
      pokedexId: 3,
      nom: 'Venusaur',
      type1: 'Grass',
      type2: 'Poison',
      total: 525,
      pv: 80,
      att: 82,
      def: 83,
      attspe: 100,
      defspe: 100,
    },
    {
      pokedexId: 4,
      nom: 'Charmander',
      type1: 'Fire',
      type2: '',
      total: 309,
      pv: 39,
      att: 52,
      def: 43,
      attspe: 60,
      defspe: 50,
    },
    {
      pokedexId: 5,
      nom: 'Charmeleon',
      type1: 'Fire',
      type2: '',
      total: 405,
      pv: 58,
      att: 64,
      def: 58,
      attspe: 80,
      defspe: 65,
    },
    {
      pokedexId: 6,
      nom: 'Charizard',
      type1: 'Fire',
      type2: 'Flying',
      total: 534,
      pv: 78,
      att: 84,
      def: 78,
      attspe: 109,
      defspe: 85,
    },
    {
      pokedexId: 7,
      nom: 'Squirtle',
      type1: 'Water',
      type2: '',
      total: 314,
      pv: 44,
      att: 48,
      def: 65,
      attspe: 50,
      defspe: 64,
    },
    {
      pokedexId: 8,
      nom: 'Wartortle',
      type1: 'Water',
      type2: '',
      total: 405,
      pv: 59,
      att: 63,
      def: 80,
      attspe: 65,
      defspe: 80,
    },
    {
      pokedexId: 9,
      nom: 'Blastoise',
      type1: 'Water',
      type2: '',
      total: 530,
      pv: 79,
      att: 83,
      def: 100,
      attspe: 85,
      defspe: 105,
    },
    {
      pokedexId: 10,
      nom: 'Caterpie',
      type1: 'Bug',
      type2: '',
      total: 195,
      pv: 45,
      att: 30,
      def: 35,
      attspe: 20,
      defspe: 20,
    },
    {
      pokedexId: 11,
      nom: 'Metapod',
      type1: 'Bug',
      type2: '',
      total: 205,
      pv: 50,
      att: 20,
      def: 55,
      attspe: 25,
      defspe: 25,
    },
    {
      pokedexId: 12,
      nom: 'Butterfree',
      type1: 'Bug',
      type2: 'Flying',
      total: 395,
      pv: 60,
      att: 45,
      def: 50,
      attspe: 90,
      defspe: 80,
    },
    {
      pokedexId: 13,
      nom: 'Weedle',
      type1: 'Bug',
      type2: 'Poison',
      total: 195,
      pv: 40,
      att: 35,
      def: 30,
      attspe: 20,
      defspe: 20,
    },
    {
      pokedexId: 14,
      nom: 'Kakuna',
      type1: 'Bug',
      type2: 'Poison',
      total: 205,
      pv: 45,
      att: 25,
      def: 50,
      attspe: 25,
      defspe: 25,
    },
    {
      pokedexId: 15,
      nom: 'Beedrill',
      type1: 'Bug',
      type2: 'Poison',
      total: 395,
      pv: 65,
      att: 90,
      def: 40,
      attspe: 45,
      defspe: 80,
    },
    {
      pokedexId: 16,
      nom: 'Pidgey',
      type1: 'Normal',
      type2: 'Flying',
      total: 251,
      pv: 40,
      att: 45,
      def: 40,
      attspe: 35,
      defspe: 35,
    },
    {
      pokedexId: 17,
      nom: 'Pidgeotto',
      type1: 'Normal',
      type2: 'Flying',
      total: 349,
      pv: 63,
      att: 60,
      def: 55,
      attspe: 50,
      defspe: 50,
    },
    {
      pokedexId: 18,
      nom: 'Pidgeot',
      type1: 'Normal',
      type2: 'Flying',
      total: 479,
      pv: 83,
      att: 80,
      def: 75,
      attspe: 70,
      defspe: 70,
    },
    {
      pokedexId: 19,
      nom: 'Rattata',
      type1: 'Normal',
      type2: '',
      total: 253,
      pv: 30,
      att: 56,
      def: 35,
      attspe: 25,
      defspe: 35,
    },
    {
      pokedexId: 20,
      nom: 'Raticate',
      type1: 'Normal',
      type2: '',
      total: 413,
      pv: 55,
      att: 81,
      def: 60,
      attspe: 50,
      defspe: 70,
    },
    {
      pokedexId: 21,
      nom: 'Spearow',
      type1: 'Normal',
      type2: 'Flying',
      total: 262,
      pv: 40,
      att: 60,
      def: 30,
      attspe: 31,
      defspe: 31,
    },
    {
      pokedexId: 22,
      nom: 'Fearow',
      type1: 'Normal',
      type2: 'Flying',
      total: 442,
      pv: 65,
      att: 90,
      def: 65,
      attspe: 61,
      defspe: 61,
    },
    {
      pokedexId: 23,
      nom: 'Ekans',
      type1: 'Poison',
      type2: '',
      total: 288,
      pv: 35,
      att: 60,
      def: 44,
      attspe: 40,
      defspe: 54,
    },
    {
      pokedexId: 24,
      nom: 'Arbok',
      type1: 'Poison',
      type2: '',
      total: 438,
      pv: 60,
      att: 85,
      def: 69,
      attspe: 65,
      defspe: 79,
    },
    {
      pokedexId: 25,
      nom: 'Pikachu',
      type1: 'Electric',
      type2: '',
      total: 320,
      pv: 35,
      att: 55,
      def: 40,
      attspe: 50,
      defspe: 50,
    },
    {
      pokedexId: 26,
      nom: 'Raichu',
      type1: 'Electric',
      type2: '',
      total: 485,
      pv: 60,
      att: 90,
      def: 55,
      attspe: 90,
      defspe: 80,
    },
    {
      pokedexId: 27,
      nom: 'Sandshrew',
      type1: 'Ground',
      type2: '',
      total: 300,
      pv: 50,
      att: 75,
      def: 85,
      attspe: 20,
      defspe: 30,
    },
    {
      pokedexId: 28,
      nom: 'Sandslash',
      type1: 'Ground',
      type2: '',
      total: 450,
      pv: 75,
      att: 100,
      def: 110,
      attspe: 45,
      defspe: 55,
    },
    {
      pokedexId: 29,
      nom: 'Nidoran♀',
      type1: 'Poison',
      type2: '',
      total: 275,
      pv: 55,
      att: 47,
      def: 52,
      attspe: 40,
      defspe: 40,
    },
    {
      pokedexId: 30,
      nom: 'Nidorina',
      type1: 'Poison',
      type2: '',
      total: 365,
      pv: 70,
      att: 62,
      def: 67,
      attspe: 55,
      defspe: 55,
    },
    {
      pokedexId: 31,
      nom: 'Nidoqueen',
      type1: 'Poison',
      type2: 'Ground',
      total: 505,
      pv: 90,
      att: 92,
      def: 87,
      attspe: 75,
      defspe: 85,
    },
    {
      pokedexId: 32,
      nom: 'Nidoran♂',
      type1: 'Poison',
      type2: '',
      total: 273,
      pv: 46,
      att: 57,
      def: 40,
      attspe: 40,
      defspe: 40,
    },
    {
      pokedexId: 33,
      nom: 'Nidorino',
      type1: 'Poison',
      type2: '',
      total: 365,
      pv: 61,
      att: 72,
      def: 57,
      attspe: 55,
      defspe: 55,
    },
    {
      pokedexId: 34,
      nom: 'Nidoking',
      type1: 'Poison',
      type2: 'Ground',
      total: 505,
      pv: 81,
      att: 102,
      def: 77,
      attspe: 85,
      defspe: 75,
    },
    {
      pokedexId: 35,
      nom: 'Clefairy',
      type1: 'Fairy',
      type2: '',
      total: 323,
      pv: 70,
      att: 45,
      def: 48,
      attspe: 60,
      defspe: 65,
    },
    {
      pokedexId: 36,
      nom: 'Clefable',
      type1: 'Fairy',
      type2: '',
      total: 483,
      pv: 95,
      att: 70,
      def: 73,
      attspe: 95,
      defspe: 90,
    },
    {
      pokedexId: 37,
      nom: 'Vulpix',
      type1: 'Fire',
      type2: '',
      total: 299,
      pv: 38,
      att: 41,
      def: 40,
      attspe: 50,
      defspe: 65,
    },
    {
      pokedexId: 38,
      nom: 'Ninetales',
      type1: 'Fire',
      type2: '',
      total: 505,
      pv: 73,
      att: 76,
      def: 75,
      attspe: 81,
      defspe: 100,
    },
    {
      pokedexId: 39,
      nom: 'Jigglypuff',
      type1: 'Normal',
      type2: 'Fairy',
      total: 270,
      pv: 115,
      att: 45,
      def: 20,
      attspe: 45,
      defspe: 25,
    },
    {
      pokedexId: 40,
      nom: 'Wigglytuff',
      type1: 'Normal',
      type2: 'Fairy',
      total: 435,
      pv: 140,
      att: 70,
      def: 45,
      attspe: 85,
      defspe: 50,
    },
    {
      pokedexId: 41,
      nom: 'Zubat',
      type1: 'Poison',
      type2: 'Flying',
      total: 245,
      pv: 40,
      att: 45,
      def: 35,
      attspe: 30,
      defspe: 40,
    },
    {
      pokedexId: 42,
      nom: 'Golbat',
      type1: 'Poison',
      type2: 'Flying',
      total: 455,
      pv: 75,
      att: 80,
      def: 70,
      attspe: 65,
      defspe: 75,
    },
    {
      pokedexId: 43,
      nom: 'Oddish',
      type1: 'Grass',
      type2: 'Poison',
      total: 320,
      pv: 45,
      att: 50,
      def: 55,
      attspe: 75,
      defspe: 65,
    },
    {
      pokedexId: 44,
      nom: 'Gloom',
      type1: 'Grass',
      type2: 'Poison',
      total: 395,
      pv: 60,
      att: 65,
      def: 70,
      attspe: 85,
      defspe: 75,
    },
    {
      pokedexId: 45,
      nom: 'Vileplume',
      type1: 'Grass',
      type2: 'Poison',
      total: 490,
      pv: 75,
      att: 80,
      def: 85,
      attspe: 110,
      defspe: 90,
    },
    {
      pokedexId: 46,
      nom: 'Paras',
      type1: 'Bug',
      type2: 'Grass',
      total: 285,
      pv: 35,
      att: 70,
      def: 55,
      attspe: 45,
      defspe: 55,
    },
    {
      pokedexId: 47,
      nom: 'Parasect',
      type1: 'Bug',
      type2: 'Grass',
      total: 405,
      pv: 60,
      att: 95,
      def: 80,
      attspe: 60,
      defspe: 80,
    },
    {
      pokedexId: 48,
      nom: 'Venonat',
      type1: 'Bug',
      type2: 'Poison',
      total: 305,
      pv: 60,
      att: 55,
      def: 50,
      attspe: 40,
      defspe: 55,
    },
    {
      pokedexId: 49,
      nom: 'Venomoth',
      type1: 'Bug',
      type2: 'Poison',
      total: 450,
      pv: 70,
      att: 65,
      def: 60,
      attspe: 90,
      defspe: 75,
    },
    {
      pokedexId: 50,
      nom: 'Diglett',
      type1: 'Ground',
      type2: '',
      total: 265,
      pv: 10,
      att: 55,
      def: 25,
      attspe: 35,
      defspe: 45,
    },
    {
      pokedexId: 51,
      nom: 'Dugtrio',
      type1: 'Ground',
      type2: '',
      total: 405,
      pv: 35,
      att: 80,
      def: 50,
      attspe: 50,
      defspe: 70,
    },
    {
      pokedexId: 52,
      nom: 'Meowth',
      type1: 'Normal',
      type2: '',
      total: 290,
      pv: 40,
      att: 45,
      def: 35,
      attspe: 40,
      defspe: 40,
    },
    {
      pokedexId: 53,
      nom: 'Persian',
      type1: 'Normal',
      type2: '',
      total: 440,
      pv: 65,
      att: 70,
      def: 60,
      attspe: 65,
      defspe: 65,
    },
    {
      pokedexId: 54,
      nom: 'Psyduck',
      type1: 'Water',
      type2: '',
      total: 320,
      pv: 50,
      att: 52,
      def: 48,
      attspe: 65,
      defspe: 50,
    },
    {
      pokedexId: 55,
      nom: 'Golduck',
      type1: 'Water',
      type2: '',
      total: 500,
      pv: 80,
      att: 82,
      def: 78,
      attspe: 95,
      defspe: 80,
    },
    {
      pokedexId: 56,
      nom: 'Mankey',
      type1: 'Fighting',
      type2: '',
      total: 305,
      pv: 40,
      att: 80,
      def: 35,
      attspe: 35,
      defspe: 45,
    },
    {
      pokedexId: 57,
      nom: 'Primeape',
      type1: 'Fighting',
      type2: '',
      total: 455,
      pv: 65,
      att: 105,
      def: 60,
      attspe: 60,
      defspe: 70,
    },
    {
      pokedexId: 58,
      nom: 'Growlithe',
      type1: 'Fire',
      type2: '',
      total: 350,
      pv: 55,
      att: 70,
      def: 45,
      attspe: 70,
      defspe: 50,
    },
    {
      pokedexId: 59,
      nom: 'Arcanine',
      type1: 'Fire',
      type2: '',
      total: 555,
      pv: 90,
      att: 110,
      def: 80,
      attspe: 100,
      defspe: 80,
    },
    {
      pokedexId: 60,
      nom: 'Poliwag',
      type1: 'Water',
      type2: '',
      total: 300,
      pv: 40,
      att: 50,
      def: 40,
      attspe: 40,
      defspe: 40,
    },
    {
      pokedexId: 61,
      nom: 'Poliwhirl',
      type1: 'Water',
      type2: '',
      total: 385,
      pv: 65,
      att: 65,
      def: 65,
      attspe: 50,
      defspe: 50,
    },
    {
      pokedexId: 62,
      nom: 'Poliwrath',
      type1: 'Water',
      type2: 'Fighting',
      total: 510,
      pv: 90,
      att: 95,
      def: 95,
      attspe: 70,
      defspe: 90,
    },
    {
      pokedexId: 63,
      nom: 'Abra',
      type1: 'Psychic',
      type2: '',
      total: 310,
      pv: 25,
      att: 20,
      def: 15,
      attspe: 105,
      defspe: 55,
    },
    {
      pokedexId: 64,
      nom: 'Kadabra',
      type1: 'Psychic',
      type2: '',
      total: 400,
      pv: 40,
      att: 35,
      def: 30,
      attspe: 120,
      defspe: 70,
    },
    {
      pokedexId: 65,
      nom: 'Alakazam',
      type1: 'Psychic',
      type2: '',
      total: 500,
      pv: 55,
      att: 50,
      def: 45,
      attspe: 135,
      defspe: 95,
    },
    {
      pokedexId: 66,
      nom: 'Machop',
      type1: 'Fighting',
      type2: '',
      total: 305,
      pv: 70,
      att: 80,
      def: 50,
      attspe: 35,
      defspe: 35,
    },
    {
      pokedexId: 67,
      nom: 'Machoke',
      type1: 'Fighting',
      type2: '',
      total: 405,
      pv: 80,
      att: 100,
      def: 70,
      attspe: 50,
      defspe: 60,
    },
    {
      pokedexId: 68,
      nom: 'Machamp',
      type1: 'Fighting',
      type2: '',
      total: 505,
      pv: 90,
      att: 130,
      def: 80,
      attspe: 65,
      defspe: 85,
    },
    {
      pokedexId: 69,
      nom: 'Bellsprout',
      type1: 'Grass',
      type2: 'Poison',
      total: 300,
      pv: 50,
      att: 75,
      def: 35,
      attspe: 70,
      defspe: 30,
    },
    {
      pokedexId: 70,
      nom: 'Weepinbell',
      type1: 'Grass',
      type2: 'Poison',
      total: 390,
      pv: 65,
      att: 90,
      def: 50,
      attspe: 85,
      defspe: 45,
    },
    {
      pokedexId: 71,
      nom: 'Victreebel',
      type1: 'Grass',
      type2: 'Poison',
      total: 490,
      pv: 80,
      att: 105,
      def: 65,
      attspe: 100,
      defspe: 70,
    },
    {
      pokedexId: 72,
      nom: 'Tentacool',
      type1: 'Water',
      type2: 'Poison',
      total: 335,
      pv: 40,
      att: 40,
      def: 35,
      attspe: 50,
      defspe: 100,
    },
    {
      pokedexId: 73,
      nom: 'Tentacruel',
      type1: 'Water',
      type2: 'Poison',
      total: 515,
      pv: 80,
      att: 70,
      def: 65,
      attspe: 80,
      defspe: 120,
    },
    {
      pokedexId: 74,
      nom: 'Geodude',
      type1: 'Rock',
      type2: 'Ground',
      total: 300,
      pv: 40,
      att: 80,
      def: 100,
      attspe: 30,
      defspe: 30,
    },
    {
      pokedexId: 75,
      nom: 'Graveler',
      type1: 'Rock',
      type2: 'Ground',
      total: 390,
      pv: 55,
      att: 95,
      def: 115,
      attspe: 45,
      defspe: 45,
    },
    {
      pokedexId: 76,
      nom: 'Golem',
      type1: 'Rock',
      type2: 'Ground',
      total: 495,
      pv: 80,
      att: 120,
      def: 130,
      attspe: 55,
      defspe: 65,
    },
    {
      pokedexId: 77,
      nom: 'Ponyta',
      type1: 'Fire',
      type2: '',
      total: 410,
      pv: 50,
      att: 85,
      def: 55,
      attspe: 65,
      defspe: 65,
    },
    {
      pokedexId: 78,
      nom: 'Rapidash',
      type1: 'Fire',
      type2: '',
      total: 500,
      pv: 65,
      att: 100,
      def: 70,
      attspe: 80,
      defspe: 80,
    },
    {
      pokedexId: 79,
      nom: 'Slowpoke',
      type1: 'Water',
      type2: 'Psychic',
      total: 315,
      pv: 90,
      att: 65,
      def: 65,
      attspe: 40,
      defspe: 40,
    },
    {
      pokedexId: 80,
      nom: 'Slowbro',
      type1: 'Water',
      type2: 'Psychic',
      total: 490,
      pv: 95,
      att: 75,
      def: 110,
      attspe: 100,
      defspe: 80,
    },
    {
      pokedexId: 81,
      nom: 'Magnemite',
      type1: 'Electric',
      type2: 'Steel',
      total: 325,
      pv: 25,
      att: 35,
      def: 70,
      attspe: 95,
      defspe: 55,
    },
    {
      pokedexId: 82,
      nom: 'Magneton',
      type1: 'Electric',
      type2: 'Steel',
      total: 465,
      pv: 50,
      att: 60,
      def: 95,
      attspe: 120,
      defspe: 70,
    },
    {
      pokedexId: 83,
      nom: "Farfetch'd",
      type1: 'Normal',
      type2: 'Flying',
      total: 352,
      pv: 52,
      att: 65,
      def: 55,
      attspe: 58,
      defspe: 62,
    },
    {
      pokedexId: 84,
      nom: 'Doduo',
      type1: 'Normal',
      type2: 'Flying',
      total: 310,
      pv: 35,
      att: 85,
      def: 45,
      attspe: 35,
      defspe: 35,
    },
    {
      pokedexId: 85,
      nom: 'Dodrio',
      type1: 'Normal',
      type2: 'Flying',
      total: 460,
      pv: 60,
      att: 110,
      def: 70,
      attspe: 60,
      defspe: 60,
    },
    {
      pokedexId: 86,
      nom: 'Seel',
      type1: 'Water',
      type2: '',
      total: 325,
      pv: 65,
      att: 45,
      def: 55,
      attspe: 45,
      defspe: 70,
    },
    {
      pokedexId: 87,
      nom: 'Dewgong',
      type1: 'Water',
      type2: 'Ice',
      total: 475,
      pv: 90,
      att: 70,
      def: 80,
      attspe: 70,
      defspe: 95,
    },
    {
      pokedexId: 88,
      nom: 'Grimer',
      type1: 'Poison',
      type2: '',
      total: 325,
      pv: 80,
      att: 80,
      def: 50,
      attspe: 40,
      defspe: 50,
    },
    {
      pokedexId: 89,
      nom: 'Muk',
      type1: 'Poison',
      type2: '',
      total: 500,
      pv: 105,
      att: 105,
      def: 75,
      attspe: 65,
      defspe: 100,
    },
    {
      pokedexId: 90,
      nom: 'Shellder',
      type1: 'Water',
      type2: '',
      total: 305,
      pv: 30,
      att: 65,
      def: 100,
      attspe: 45,
      defspe: 25,
    },
    {
      pokedexId: 91,
      nom: 'Cloyster',
      type1: 'Water',
      type2: 'Ice',
      total: 525,
      pv: 50,
      att: 95,
      def: 180,
      attspe: 85,
      defspe: 45,
    },
    {
      pokedexId: 92,
      nom: 'Gastly',
      type1: 'Ghost',
      type2: 'Poison',
      total: 310,
      pv: 30,
      att: 35,
      def: 30,
      attspe: 100,
      defspe: 35,
    },
    {
      pokedexId: 93,
      nom: 'Haunter',
      type1: 'Ghost',
      type2: 'Poison',
      total: 405,
      pv: 45,
      att: 50,
      def: 45,
      attspe: 115,
      defspe: 55,
    },
    {
      pokedexId: 94,
      nom: 'Gengar',
      type1: 'Ghost',
      type2: 'Poison',
      total: 500,
      pv: 60,
      att: 65,
      def: 60,
      attspe: 130,
      defspe: 75,
    },
    {
      pokedexId: 95,
      nom: 'Onix',
      type1: 'Rock',
      type2: 'Ground',
      total: 385,
      pv: 35,
      att: 45,
      def: 160,
      attspe: 30,
      defspe: 45,
    },
    {
      pokedexId: 96,
      nom: 'Drowzee',
      type1: 'Psychic',
      type2: '',
      total: 328,
      pv: 60,
      att: 48,
      def: 45,
      attspe: 43,
      defspe: 90,
    },
    {
      pokedexId: 97,
      nom: 'Hypno',
      type1: 'Psychic',
      type2: '',
      total: 483,
      pv: 85,
      att: 73,
      def: 70,
      attspe: 73,
      defspe: 115,
    },
    {
      pokedexId: 98,
      nom: 'Krabby',
      type1: 'Water',
      type2: '',
      total: 325,
      pv: 30,
      att: 105,
      def: 90,
      attspe: 25,
      defspe: 25,
    },
    {
      pokedexId: 99,
      nom: 'Kingler',
      type1: 'Water',
      type2: '',
      total: 475,
      pv: 55,
      att: 130,
      def: 115,
      attspe: 50,
      defspe: 50,
    },
    {
      pokedexId: 100,
      nom: 'Voltorb',
      type1: 'Electric',
      type2: '',
      total: 330,
      pv: 40,
      att: 30,
      def: 50,
      attspe: 55,
      defspe: 55,
    },
    {
      pokedexId: 101,
      nom: 'Electrode',
      type1: 'Electric',
      type2: '',
      total: 480,
      pv: 60,
      att: 50,
      def: 70,
      attspe: 80,
      defspe: 80,
    },
    {
      pokedexId: 102,
      nom: 'Exeggcute',
      type1: 'Grass',
      type2: 'Psychic',
      total: 325,
      pv: 60,
      att: 40,
      def: 80,
      attspe: 60,
      defspe: 45,
    },
    {
      pokedexId: 103,
      nom: 'Exeggutor',
      type1: 'Grass',
      type2: 'Psychic',
      total: 520,
      pv: 95,
      att: 95,
      def: 85,
      attspe: 125,
      defspe: 65,
    },
    {
      pokedexId: 104,
      nom: 'Cubone',
      type1: 'Ground',
      type2: '',
      total: 320,
      pv: 50,
      att: 50,
      def: 95,
      attspe: 40,
      defspe: 50,
    },
    {
      pokedexId: 105,
      nom: 'Marowak',
      type1: 'Ground',
      type2: '',
      total: 425,
      pv: 60,
      att: 80,
      def: 110,
      attspe: 50,
      defspe: 80,
    },
    {
      pokedexId: 106,
      nom: 'Hitmonlee',
      type1: 'Fighting',
      type2: '',
      total: 455,
      pv: 50,
      att: 120,
      def: 53,
      attspe: 35,
      defspe: 110,
    },
    {
      pokedexId: 107,
      nom: 'Hitmonchan',
      type1: 'Fighting',
      type2: '',
      total: 455,
      pv: 50,
      att: 105,
      def: 79,
      attspe: 35,
      defspe: 110,
    },
    {
      pokedexId: 108,
      nom: 'Lickitung',
      type1: 'Normal',
      type2: '',
      total: 385,
      pv: 90,
      att: 55,
      def: 75,
      attspe: 60,
      defspe: 75,
    },
    {
      pokedexId: 109,
      nom: 'Koffing',
      type1: 'Poison',
      type2: '',
      total: 340,
      pv: 40,
      att: 65,
      def: 95,
      attspe: 60,
      defspe: 45,
    },
    {
      pokedexId: 110,
      nom: 'Weezing',
      type1: 'Poison',
      type2: '',
      total: 490,
      pv: 65,
      att: 90,
      def: 120,
      attspe: 85,
      defspe: 70,
    },
    {
      pokedexId: 111,
      nom: 'Rhyhorn',
      type1: 'Ground',
      type2: 'Rock',
      total: 345,
      pv: 80,
      att: 85,
      def: 95,
      attspe: 30,
      defspe: 30,
    },
    {
      pokedexId: 112,
      nom: 'Rhydon',
      type1: 'Ground',
      type2: 'Rock',
      total: 485,
      pv: 105,
      att: 130,
      def: 120,
      attspe: 45,
      defspe: 45,
    },
    {
      pokedexId: 113,
      nom: 'Chansey',
      type1: 'Normal',
      type2: '',
      total: 450,
      pv: 250,
      att: 5,
      def: 5,
      attspe: 35,
      defspe: 105,
    },
    {
      pokedexId: 114,
      nom: 'Tangela',
      type1: 'Grass',
      type2: '',
      total: 435,
      pv: 65,
      att: 55,
      def: 115,
      attspe: 100,
      defspe: 40,
    },
    {
      pokedexId: 115,
      nom: 'Kangaskhan',
      type1: 'Normal',
      type2: '',
      total: 490,
      pv: 105,
      att: 95,
      def: 80,
      attspe: 40,
      defspe: 80,
    },
    {
      pokedexId: 116,
      nom: 'Horsea',
      type1: 'Water',
      type2: '',
      total: 295,
      pv: 30,
      att: 40,
      def: 70,
      attspe: 70,
      defspe: 25,
    },
    {
      pokedexId: 117,
      nom: 'Seadra',
      type1: 'Water',
      type2: '',
      total: 440,
      pv: 55,
      att: 65,
      def: 95,
      attspe: 95,
      defspe: 45,
    },
    {
      pokedexId: 118,
      nom: 'Goldeen',
      type1: 'Water',
      type2: '',
      total: 320,
      pv: 45,
      att: 67,
      def: 60,
      attspe: 35,
      defspe: 50,
    },
    {
      pokedexId: 119,
      nom: 'Seaking',
      type1: 'Water',
      type2: '',
      total: 450,
      pv: 80,
      att: 92,
      def: 65,
      attspe: 65,
      defspe: 80,
    },
    {
      pokedexId: 120,
      nom: 'Staryu',
      type1: 'Water',
      type2: '',
      total: 340,
      pv: 30,
      att: 45,
      def: 55,
      attspe: 70,
      defspe: 55,
    },
    {
      pokedexId: 121,
      nom: 'Starmie',
      type1: 'Water',
      type2: 'Psychic',
      total: 520,
      pv: 60,
      att: 75,
      def: 85,
      attspe: 100,
      defspe: 85,
    },
    {
      pokedexId: 122,
      nom: 'Mr. Mime',
      type1: 'Psychic',
      type2: 'Fairy',
      total: 460,
      pv: 40,
      att: 45,
      def: 65,
      attspe: 100,
      defspe: 120,
    },
    {
      pokedexId: 123,
      nom: 'Scyther',
      type1: 'Bug',
      type2: 'Flying',
      total: 500,
      pv: 70,
      att: 110,
      def: 80,
      attspe: 55,
      defspe: 80,
    },
    {
      pokedexId: 124,
      nom: 'Jynx',
      type1: 'Ice',
      type2: 'Psychic',
      total: 455,
      pv: 65,
      att: 50,
      def: 35,
      attspe: 115,
      defspe: 95,
    },
    {
      pokedexId: 125,
      nom: 'Electabuzz',
      type1: 'Electric',
      type2: '',
      total: 490,
      pv: 65,
      att: 83,
      def: 57,
      attspe: 95,
      defspe: 85,
    },
    {
      pokedexId: 126,
      nom: 'Magmar',
      type1: 'Fire',
      type2: '',
      total: 495,
      pv: 65,
      att: 95,
      def: 57,
      attspe: 100,
      defspe: 85,
    },
    {
      pokedexId: 127,
      nom: 'Pinsir',
      type1: 'Bug',
      type2: '',
      total: 500,
      pv: 65,
      att: 125,
      def: 100,
      attspe: 55,
      defspe: 70,
    },
    {
      pokedexId: 128,
      nom: 'Tauros',
      type1: 'Normal',
      type2: '',
      total: 490,
      pv: 75,
      att: 100,
      def: 95,
      attspe: 40,
      defspe: 70,
    },
    {
      pokedexId: 129,
      nom: 'Magikarp',
      type1: 'Water',
      type2: '',
      total: 200,
      pv: 20,
      att: 10,
      def: 55,
      attspe: 15,
      defspe: 20,
    },
    {
      pokedexId: 130,
      nom: 'Gyarados',
      type1: 'Water',
      type2: 'Flying',
      total: 540,
      pv: 95,
      att: 125,
      def: 79,
      attspe: 60,
      defspe: 100,
    },
    {
      pokedexId: 131,
      nom: 'Lapras',
      type1: 'Water',
      type2: 'Ice',
      total: 535,
      pv: 130,
      att: 85,
      def: 80,
      attspe: 85,
      defspe: 95,
    },
    {
      pokedexId: 132,
      nom: 'Ditto',
      type1: 'Normal',
      type2: '',
      total: 288,
      pv: 48,
      att: 48,
      def: 48,
      attspe: 48,
      defspe: 48,
    },
    {
      pokedexId: 133,
      nom: 'Eevee',
      type1: 'Normal',
      type2: '',
      total: 325,
      pv: 55,
      att: 55,
      def: 50,
      attspe: 45,
      defspe: 65,
    },
    {
      pokedexId: 134,
      nom: 'Vaporeon',
      type1: 'Water',
      type2: '',
      total: 525,
      pv: 130,
      att: 65,
      def: 60,
      attspe: 110,
      defspe: 95,
    },
    {
      pokedexId: 135,
      nom: 'Jolteon',
      type1: 'Electric',
      type2: '',
      total: 525,
      pv: 65,
      att: 65,
      def: 60,
      attspe: 110,
      defspe: 95,
    },
    {
      pokedexId: 136,
      nom: 'Flareon',
      type1: 'Fire',
      type2: '',
      total: 525,
      pv: 65,
      att: 130,
      def: 60,
      attspe: 95,
      defspe: 110,
    },
    {
      pokedexId: 137,
      nom: 'Porygon',
      type1: 'Normal',
      type2: '',
      total: 395,
      pv: 65,
      att: 60,
      def: 70,
      attspe: 85,
      defspe: 75,
    },
    {
      pokedexId: 138,
      nom: 'Omanyte',
      type1: 'Rock',
      type2: 'Water',
      total: 355,
      pv: 35,
      att: 40,
      def: 100,
      attspe: 90,
      defspe: 55,
    },
    {
      pokedexId: 139,
      nom: 'Omastar',
      type1: 'Rock',
      type2: 'Water',
      total: 495,
      pv: 70,
      att: 60,
      def: 125,
      attspe: 115,
      defspe: 70,
    },
    {
      pokedexId: 140,
      nom: 'Kabuto',
      type1: 'Rock',
      type2: 'Water',
      total: 355,
      pv: 30,
      att: 80,
      def: 90,
      attspe: 55,
      defspe: 45,
    },
    {
      pokedexId: 141,
      nom: 'Kabutops',
      type1: 'Rock',
      type2: 'Water',
      total: 495,
      pv: 60,
      att: 115,
      def: 105,
      attspe: 65,
      defspe: 70,
    },
    {
      pokedexId: 142,
      nom: 'Aerodactyl',
      type1: 'Rock',
      type2: 'Flying',
      total: 515,
      pv: 80,
      att: 105,
      def: 65,
      attspe: 60,
      defspe: 75,
    },
    {
      pokedexId: 143,
      nom: 'Snorlax',
      type1: 'Normal',
      type2: '',
      total: 540,
      pv: 160,
      att: 110,
      def: 65,
      attspe: 65,
      defspe: 110,
    },
    {
      pokedexId: 144,
      nom: 'Articuno',
      type1: 'Ice',
      type2: 'Flying',
      total: 580,
      pv: 90,
      att: 85,
      def: 100,
      attspe: 95,
      defspe: 125,
    },
    {
      pokedexId: 145,
      nom: 'Zapdos',
      type1: 'Electric',
      type2: 'Flying',
      total: 580,
      pv: 90,
      att: 90,
      def: 85,
      attspe: 125,
      defspe: 90,
    },
    {
      pokedexId: 146,
      nom: 'Moltres',
      type1: 'Fire',
      type2: 'Flying',
      total: 580,
      pv: 90,
      att: 100,
      def: 90,
      attspe: 125,
      defspe: 85,
    },
    {
      pokedexId: 147,
      nom: 'Dratini',
      type1: 'Dragon',
      type2: '',
      total: 300,
      pv: 41,
      att: 64,
      def: 45,
      attspe: 50,
      defspe: 50,
    },
    {
      pokedexId: 148,
      nom: 'Dragonair',
      type1: 'Dragon',
      type2: '',
      total: 420,
      pv: 61,
      att: 84,
      def: 65,
      attspe: 70,
      defspe: 70,
    },
    {
      pokedexId: 149,
      nom: 'Dragonite',
      type1: 'Dragon',
      type2: 'Flying',
      total: 600,
      pv: 91,
      att: 134,
      def: 95,
      attspe: 100,
      defspe: 100,
    },
    {
      pokedexId: 150,
      nom: 'Mewtwo',
      type1: 'Psychic',
      type2: '',
      total: 680,
      pv: 106,
      att: 110,
      def: 90,
      attspe: 154,
      defspe: 90,
    },
    {
      pokedexId: 151,
      nom: 'Mew',
      type1: 'Psychic',
      type2: '',
      total: 600,
      pv: 100,
      att: 100,
      def: 100,
      attspe: 100,
      defspe: 100,
    },
  ],;
